services:
  db:
    image: timescale/timescaledb:2.16.1-pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:8080"

  scheduler:
    build:
      context: .
      dockerfile: services/scheduler/Dockerfile
    env_file: .env
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    env_file: .env
    volumes:
      - ./flows:/app/flows
      - ./libs:/app/libs
      - ./configs:/app/configs
    depends_on:
      - scheduler
      - db

  metabase:
    image: metabase/metabase:v0.49.13
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: ${MB_DB_FILE}
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  redis_data:
  metabase_data:
